trigger: none


# variables at pipeline level
variables:
- template: /Pipelines/Variables/Policies/Paths_var.yml
- template: /Pipelines/Variables/Policies/Pipeline_scope_var.yml


resources:
  pipelines:
  - pipeline: Auto_Trigger_for_Azure_Policies  # Name of the pipeline resource
    project: CGI-SEAL-Team-Bravo
    source: 1.0 - Initial Verification # Name of the triggering pipeline
    trigger: 
      branches:
      - LJ-Branch
       

stages: 
- stage: Policies_Deployment
  displayName: "Policies_Deployment"
  jobs:
    - job: Policies_Deployment_job
      pool: 
        vmImage: ${{variables.vmImage}}
      steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{variables.Azure_Service_Principal_Connection}}
            ScriptType: 'InlineScript'
            Inline: |
              .\Policy_Deployment.ps1
            errorActionPreference: 'stop'
            azurePowerShellVersion: 'LatestVersion'
            workingDirectory: ${{variables.Powershell_Triggers_path}}            


- stage: Initiatives_Deployment
  displayName: "Initiatives_Deployment"
  dependsOn: Policies_Deployment
  jobs:
    - job: Initiatives_Deployment_job
      pool: 
        vmImage: ${{variables.vmImage}}
      steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{variables.Azure_Service_Principal_Connection}}
            ScriptType: 'InlineScript'
            Inline: |
              Write-Host "Place for PowerShell script for Initiatives deployment."
            errorActionPreference: 'stop'
            azurePowerShellVersion: 'LatestVersion'
            workingDirectory: ${{variables.Powershell_Triggers_path}}