trigger: none


# variables at pipeline level
variables:
- template: /Pipelines/Variables/Paths_var.yml
- template: /Pipelines/Variables/Pipeline_scope_var.yml


resources:
  pipelines:
  - pipeline: Auto_Trigger_for_Pipeline-01  # Name of the pipeline resource
    project:  ${{ variables.projectname }}
    source: Pipeline-01 # Name of the triggering pipeline
    trigger: true
  
             
    
stages: 
- stage: Stage_nr1
  displayName: "Stage_nr1"
  jobs:
    - job: Stage_nr1_job_nr1
      pool: 
        vmImage: ${{variables.vmImage}}
      steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{variables.Azure_Connection}}
            ScriptType: 'InlineScript'
            Inline: |
              .\Get-Env.ps1
            errorActionPreference: 'stop'
            azurePowerShellVersion: 'LatestVersion'
            workingDirectory: ${{variables.Powershell_Triggers_path}}            


# - stage: Stage_nr2
#   displayName: "Stage_nr2"
#   dependsOn: Stage_nr1
#   jobs:
#     - job: Stage_nr2_job_nr1
#       pool: 
#         vmImage: ${{variables.vmImage}}
#       steps:
#         - task: AzurePowerShell@5
#           inputs:
#             azureSubscription: ${{variables.Azure_Connection}}
#             ScriptType: 'InlineScript'
#             Inline: |
#               Write-Host "Place for PowerShell scripts..."
#             errorActionPreference: 'stop'
#             azurePowerShellVersion: 'LatestVersion'
#             workingDirectory: ${{variables.Powershell_Triggers_path}}