trigger: 
  branches:
    include:
      - 1.44


# variables at pipeline level
variables:
- template: /Pipelines/Variables/Paths_var.yml
- template: /Pipelines/Variables/Pipeline_scope_var.yml


# resources:
#  pipelines:
#  - pipeline: Auto_Trigger_for_P2.2  # Name of the pipeline resource
#    project: Pipelines_project
#    source: 1.0 - Initial Verification # Name of the triggering pipeline
#    trigger: 
#       branches:
#       - master

stages: 
- stage: RBAC_Deployment
  displayName: "RBAC_Deployment"
  jobs:
    - job: job_RBAC_Deployment
      pool: 
        vmImage: 'ubuntu-latest'
      steps:
        - pwsh: | 
            Write-Host 'AAAAAAAAAAAAAAAAAAAAAA' -ForegroundColor Green
          displayName: 'DP--AAAAAAAAAAAAAAAAAAAAAAAAAAA'
          name: 'N__AAAAAAAAAAAAAAAAAAAAAAAAAA'
          errorActionPreference: stop
          ignoreLASTEXITCODE: true
          continueOnError: false
          enabled: true
        